server:
  port: 5555

shiro:
  limiter:
    enable: true
    rate: 1
    capacity: 5
    await-task: false
  debug: true
  plugin-list:
    - com.mikuac.shiro.plugin.Weather
    - com.mikuac.shiro.plugin.LoginEduSystem
    - com.mikuac.shiro.plugin.IntelligentEntertainmentChat

# mysql
spring:
  datasource:
    url: jdbc:mysql://192.168.238.131:3306/qqrobot?serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  main:
    allow-circular-references: true

# mybatis-plus
mybatis-plus:
  configuration:
    # 数据库格式自动转为小驼峰
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
